spring.application.name=TorrentBackendApplication


server.port = 9090
spring.datasource.url=*88888888***************************************************
spring.datasource.username=neondb_owner
spring.datasource.password=*********************************
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# Scheduler
spring.task.scheduling.pool.size=5